name: Github Actions Demo
run-name: ${{ github.actor }} is testing out Github Actions
on:
  push:
    branches:
      - main
jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🚀 ci pipeline start 🚀"
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
