name: Github Actions Demo
run-name: ${{ github.actor }} is testing out Github Actions
on:
  branches:
    - main
jobs:
  steps:
    - run: echo "🚀 ci pipeline start 🚀"
    - name: Check out repository code
      uses: actions/checkout@v3
    - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
